/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { PuButtonShape, PuButtonSize, PuButtonType } from "./components/button/types";
export { PuButtonShape, PuButtonSize, PuButtonType } from "./components/button/types";
export namespace Components {
    interface PuButton {
        "danger": boolean;
        "disabled": boolean;
        "ghost": boolean;
        "href"?: string;
        "loading": boolean;
        "shape": PuButtonShape;
        "size": PuButtonSize;
        "type": PuButtonType;
    }
}
declare global {
    interface HTMLPuButtonElement extends Components.PuButton, HTMLStencilElement {
    }
    var HTMLPuButtonElement: {
        prototype: HTMLPuButtonElement;
        new (): HTMLPuButtonElement;
    };
    interface HTMLElementTagNameMap {
        "pu-button": HTMLPuButtonElement;
    }
}
declare namespace LocalJSX {
    interface PuButton {
        "danger"?: boolean;
        "disabled"?: boolean;
        "ghost"?: boolean;
        "href"?: string;
        "loading"?: boolean;
        "shape"?: PuButtonShape;
        "size"?: PuButtonSize;
        "type"?: PuButtonType;
    }
    interface IntrinsicElements {
        "pu-button": PuButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pu-button": LocalJSX.PuButton & JSXBase.HTMLAttributes<HTMLPuButtonElement>;
        }
    }
}
